version: "3.9"

services:
  backend:
    container_name: backend-prod
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - appLogs:/app/logs
    command: npm run start

  mongodb:
    container_name: mongodb
    image: mongo:5.0.6
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - express-mongo
    volumes:
      - data:/data/db
